name = "Time-Rift-Universe"
author = "PoiBoy34"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b1965b18d6db5cbfd2c1dc3ea5a42d5b9aed11e00ad1e7c77b79ed5392086ee"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
